### ISSUE TITLE
Fix NIHOD theme preview image

### ISSUE THREAD

**Issue by AlexVanK** [OER-WEB-TEAM/drupal-subtheme--nihod#17]
Ems, could you fix the preview image for the very child theme?
https://styleguide.od.nih.gov/admin/appearance

Copy the dimensions of this image to get it right ;) 
https://styleguide.od.nih.gov/themes/bootstrap5/screenshot.png

Once you finish, you can drop the finished image here!

**Comment by emsaiz** [comment]
![Subtheme 600x450](https://github.com/OER-WEB-TEAM/drupal-subtheme--nihod/assets/59488566/f70c75e3-f6e2-4a5e-be28-6a87e34a4903)

**Comment by AlexVanK** [comment]
Perfect!
