### ISSUE TITLE
Video (Card) - Create new component

### ISSUE THREAD

**Issue by AlexVanK** [OER-WEB-TEAM/drupal-subtheme--nihod#18]
@emsaiz 
Currently we have video component as a variation of a card...

![image](https://github.com/OER-WEB-TEAM/drupal-subtheme--nihod/assets/56647386/03a4f94f-2be1-42ab-88ab-b06e41bdf154)

We need to have it as dedicated component itself. Did we talk about this in the beginning? I thought so... but then we discarded the idea. However at the moment, I'm restructuring the flow of the documentation part of the components, and I need the video component to be separate!

Could you mock me up something with a default and variation views?

**Comment by emsaiz** [comment]
Done! I can put in the text. Let me know if you think I missed something! 
[https://xd.adobe.com/view/124158b0-1037-4ee2-b081-aef1353d537a-4712/](url) 
![image](https://github.com/OER-WEB-TEAM/drupal-subtheme--nihod/assets/59488566/508b4e01-3ad0-4334-b615-b80d7dde62b8)

**Comment by emsaiz** [comment]
These are only for YouTube videos right? Do we need to offer guidance for what people should do with non-YT video content like modules?

**Comment by AlexVanK** [comment]
Ems, I'm going to update the video layout a bit: you cannot coerce a video to fix exactly a certain area (the blue in your mockup),
because that would have to coerce also the other side of the card.

But the height of the other part of the card is defined by the amount of copy, and if there's too much copy the card just gets taller:

![Image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/56647386/6d73ce80-5336-46ec-822a-57e138a7db46)

If you reduce the copy, then the height of the card is defined by the amount of copy and width of the card itself. Eventually it all comes down to how much text there is:

![Image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/56647386/20ce22f7-2a24-4994-97d2-a3bc17205847)

Forcing the users to insert a maximum amount of words is a restriction that is next to impossible to enforce. Especially in a .gov environment, where they are very sensitive about their content, the descriptions are going to be different.

So I'll make the video be on the side, without the border so that the layout doesn't seem be so restricted by the content...

**Comment by emsaiz** [comment]
Ok thanks for letting me know! Sounds good 👍

**Comment by AlexVanK** [comment]
I also introduced a new variation -- let me know what you think
https://styleguide.od.nih.gov/components/video#collapsible-info
