### ISSUE TITLE
Toasts - New component

### ISSUE THREAD

**Issue by kime14** [OER-WEB-TEAM/drupal-subtheme--nihod#34]
To toast or not to toast. That is the question. 

https://getbootstrap.com/docs/4.3/components/toasts/

- Have it disappear after a few seconds?
- location?

**Comment by AlexVanK** [comment]
You're pointing out to an old version of Bootstrap ;)
this is the right docs: https://getbootstrap.com/docs/5.3/components/toasts/#overview
