### ISSUE TITLE
Back to Top Button - New component

### ISSUE THREAD

**Issue by emsaiz** [OER-WEB-TEAM/drupal-subtheme--nihod#35]
[https://xd.adobe.com/view/124158b0-1037-4ee2-b081-aef1353d537a-4712/](https://xd.adobe.com/view/124158b0-1037-4ee2-b081-aef1353d537a-4712/)

![image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/59488566/503a7a4e-0f6f-4451-b8b7-724e08e5f4e3)

**Comment by AlexVanK** [comment]
Taken care of: https://styleguide.od.nih.gov/components/back-to-top
and since this is a component that is built-in the system already we won't track it in the usage stats.
