### ISSUE TITLE
Key Content Term - New component

### ISSUE THREAD

**Issue by emsaiz** [OER-WEB-TEAM/drupal-subtheme--nihod#36]
I'm still working out some of the guidance wording! I can add that at a later date. 

https://xd.adobe.com/view/124158b0-1037-4ee2-b081-aef1353d537a-4712/

![image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/59488566/5ddb3e8f-6c4b-42bc-8f1b-f1e111e77cf4)

**Comment by kime87** [comment]
Please create in the design system.

**Comment by AlexVanK** [comment]
Component created
