### ISSUE TITLE
Scope Note Decision - Template Build 

### ISSUE THREAD

**Issue by emsaiz** [OER-WEB-TEAM/drupal-subtheme--nihod#38]
We (devs and designers) never made an official decision about how we want to handle scope notes. 

Some options we talked about a few weeks ago:

1.  memorize/enforce class rule
2.  dedicate summary boxes (that are pre-styled) to the scope note (could be problematic with alerts/not very flexible)
3.  content as block (could be hard to find/enforce)

Euna and I were ok with 2 or 3, but felt the final decision should be made by devs since y'all set up most of the pages in Drupal. 

Whatever we decide, we should include guidance on the Design System typography page. 

We can def meet about it again when you're setting up the templates!

**Comment by emsaiz** [comment]
**Decision 5/13:** 

Devs will designate field on Drupal for scope notes.

**Comment by kime87** [comment]
testing

**Comment by emsaiz** [comment]
7/8/24 meeting - Emrul will be adding a scope note field box on content type pages - content team can add in scope notes if they have time before launch.

**Comment by AlexVanK** [comment]
The scope note is not a template, but just a field in the content-type.
So this is a bit beyond the Design System.
