### ISSUE TITLE
Impossible drop-shadow physics!

### ISSUE THREAD

**Issue by AlexVanK** [OER-WEB-TEAM/drupal-subtheme--nihod#50]
The shadow-hover effect of the cards on the home page is physically impossible, and it makes my eyes bleed. 👁️ 🩸 

![image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/56647386/fd7fc885-33a7-4152-94e5-5e317bd1fa59)

For an object to produce a shadow when the sun is at noon, it must be lifted from the ground. If the camera is from the perspective of the sun, the more we lift the object (gets closer to us), the bigger the shadow it produced. When it gets closer to us, it should appear bigger!! BUT on the website, if we hover the card it doesn't get ANY bigger, yet it produced a shadow!!!

That is IMPOSSIBLE!! 🗡️ 💀

**Comment by kime14** [comment]
It's a nano lift off the page. You can't tell it's not getting bigger unless you inspect it. From the naked eye it works. Plus the earth is flat.

**Comment by emsaiz** [comment]
LOL I'm also ok with the current hover but if you REALLY want to change it, we could just do a fill on hover. 

1. Fill entire card with current grey color on hover (remove divider lines)
2. Fill entire card with light version of success color #EDF7F0 (remove divider lines)

![image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/59488566/e8fecc01-8826-4f88-a3fb-82f06bc8242b)

but I'm open to suggestions if you guys have any!

**Comment by AlexVanK** [comment]
No worries! I got you covered.
I fixed the physics by adding a scale effect.
Adding this as new feature, achievable by including the utility `dropshadow` on any element that supports the hover state!

![image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/56647386/c56775c6-cd5f-4205-a9e5-28001b06a5c7)
