### ISSUE TITLE
Link Component - Color Change

### ISSUE THREAD

**Issue by emsaiz** [OER-WEB-TEAM/drupal-subtheme--nihod#51]
Component Link: https://styleguide.od.nih.gov/components/link

- Current Link color: #20558A <-- this is the correct primary color for the new site but it's not the same as the new link color
- Correct link color: #005EA2 

Kinda related design need: We should have our link color, body copy color, and visited link color posted somewhere. It used to be on the colors page so now I think it should either be on our theming page and/or the typography page. Just a heads up! It's a problem I'm thinking about atm.

**Comment by emsaiz** [comment]
Euna and I were also thinking of different hover interactions for our links.  (NOT SOMETHING WE NEED TO DO NOW)

- Currently: link is darker on hover 
- We also liked what WCAG does where link underline is thicker on underlines: https://www.w3.org/TR/WCAG20-TECHS/G183.html

**Comment by AlexVanK** [comment]
Done,

here are the adjustments
```SCSS
// *
// *
// LINKS
$link-color: #005EA2 !default;
$link-shade-percentage: 40% !default;`

we won't change the decoration for now.
