### ISSUE TITLE
External Link - Module vs. Manual Discussion

### ISSUE THREAD

**Issue by emsaiz** [OER-WEB-TEAM/drupal-subtheme--nihod#62]
Just wanted to keep you posed about some of the discussions that have design system implications! 

https://styleguide.od.nih.gov/components/link#external-link

**Current guidance about how to create/add external link icon**:
 "All you need to do is make sure to include the target="_blank" attribute to your links." 

**Update**: 
- Emrul and Mauricio would rather use a Drupal module to identify and add external link icons for a few reasons: 
(1) Customers often add and manipulate external links and we want to keep them out of the source code AND limit the amount of times they would contact the webteam to add them.
(2) We have thousands of links and adding these manually would require too much time/effort and increase the chance we forget to add them.

Let us know how you feel about this! I can make changes to the external link section depending on what we decide.

**Comment by emsaiz** [comment]
Should "image as link" get it's own H2? It's overkill for the code but I feel like it follows the pattern better
![image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/59488566/045276e7-be8d-4640-a924-f68625ecd48a)

**Comment by AlexVanK** [comment]
For the first point, this does not affect the Design System. It's a logistic problem on grants, that needs to be handled there. I would open a related ticked on the grants repo. 

For the second point, I can't split the link page into an extra section as each component has only 3 variations (default + 2).
Technically image is not a variation as an image could be all 3 variations too (normal, external, anchor).
