### ISSUE TITLE
Modal H2 Labels Question

### ISSUE THREAD

**Issue by emsaiz** [OER-WEB-TEAM/drupal-subtheme--nihod#63]
Can we change the H2 headers on [modals ](**url**) page (or in general)? 

"Default" and the headers that follow usually depict design variations but in this case, I think the headers are primarily highlighting alignment and size options not necessarily design variations. 

How do you feel about changing (if possible):

- "Default" --> "Alignment" or "Alignment Options"

![image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/59488566/301b8df9-790a-4ef8-abdc-a51e5c00e5b0)

**Comment by AlexVanK** [comment]
Taken care of.
