### ISSUE TITLE
Templates - Build Several Tamplates

### ISSUE THREAD

**Issue by emsaiz** [OER-WEB-TEAM/drupal-subtheme--nihod#7]
I think you might have most/all of these done? The page is empty now and I think we need something there whether it's images or each template gets its own page with usability guidance etc.

Let me know if this is in my court and I need to make a mockup! 

Ref: http://xd.adobe.com/view/130b7f1c-6556-4551-b488-a6ae2a642e53-4658/

**Comment by AlexVanK** [comment]
It won't be possible to construct pages that simulate template pages.
Template pages are built with the underlying TWIG template engine that Drupal uses.

We can build a node for each template, e.g.:
- 404
- 403
- log-in
- etc

with a bit of a description about the template context, and perhaps a jpg preview of the template.
This requires us to update the preview image, every time we update the template file/mockup.

---

Alternative solution.

I will look into simulating the template output with an iframe -- that should render the template without any image effort.

**Comment by emsaiz** [comment]
Ok sounds good! Here are some descriptions of the templates: https://xd.adobe.com/view/124158b0-1037-4ee2-b081-aef1353d537a-4712/

![image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/59488566/786e96c3-1d51-4c0a-936b-ca7747d822c8)

**Comment by AlexVanK** [comment]
@emsaiz 
for the maintenance mode template, you can't have maintenance mode and see header, sidebar and footer -- otherwise it wouldn't be maintenance. 

In maintenance mode the site should be completely hidden. Here's how the template would look like,
let me know if you like this:

![image](https://github.com/OER-WEB-TEAM/design-system--drupal-theme/assets/56647386/c13f861d-0dd8-4049-99e6-26e8089d9136)

**Comment by emsaiz** [comment]
Ok sounds good! 

- There's a typo "with we'll be **back** soon!"
- Can we left align the logo | Design System? Or is that no part of the template?

**Comment by AlexVanK** [comment]
Taken care of.
User account templates created too: "login", "register", "pass reset"
https://styleguide.od.nih.gov/templates/user-account
