### ISSUE TITLE
Document design decisions from Grants redesign

### ISSUE THREAD

**Issue by betsy-hall** [OER-WEB-TEAM/drupal-subtheme--nihod#74]
Please document on the design system some design decisions that were made with the grants redesign.

- [x] External links: https://styleguide.od.nih.gov/components/link#external-link They don't open in a new tab. Icon is based on domain.
- [x] internal links: how do we want to tell the user that extramural-intranet links are internal? Use the lock icon and/or verbiage like "(NIH staff)"? e.g. https://grants.nih.gov/policy-and-compliance/policy-topics/peer-review
- [x] Explain that links should only open in a new tab when it would disrupt the user's task flow to stay in the current tab. examples: glossary, guide search results, links in the middle of a decision tool/form.

**Comment by betsy-hall** [comment]
@emsaiz The section about external links still talks about opening in a new tab and says to use target="_blank" to get the external link icon. https://styleguide.od.nih.gov/components/link#external-link

**Comment by emsaiz** [comment]
@betsy-hall Thanks for catching! 
@AlexVanK Do you think you could change the wording in that section if you have the chance? I'm happy to do it as well, but I didn't want to go in a delete your documentation with no warning. Lmk!

**Comment by betsy-hall** [comment]
@AlexVanK can you also please remove the target="_blank" from the sample code? https://styleguide.od.nih.gov/components/link#external-link
