### ISSUE TITLE
Accordions: auto-scroll when opening an accordion

### ISSUE THREAD

**Issue by betsy-hall** [OER-WEB-TEAM/drupal-subtheme--nihod#76]
On https://grants.nih.gov/new-to-nih, the "Who is Eligible" accordion is really long, and the "Meet the NIH Team" accordion below it is really short. If you have Who is Eligible open, then scroll down and click to open Meet the NIH Team, the viewing window stays where it is, but the content of the open accordion is above the fold. It looks to the user like the content they wanted scrolled away, and they have to scroll up to get to what they clicked on. Is it possible to make the page auto-scroll to the top of an accordion when it's clicked open? Same thing happens with the "Interacting with NIH Systems" (long) and "Get Registered" (short).

**Comment by AlexVanK** [comment]
closing as integrated into https://github.com/OER-WEB-TEAM/design-system--drupal-theme/issues/76#issue-2573982669
