### ISSUE TITLE
Update Alert Component Ghost Text

### ISSUE THREAD

**Issue by emsaiz** [OER-WEB-TEAM/drupal-subtheme--nihod#77]
### **Problem**: 
On the website, most content creators haven't updated the alert titles. The "Info Alert" ghost text is intended to label the component, not serve as a permanent title (example: https://grants.nih.gov/funding/funding-categories/research-training-and-career-development/individual-fellowships). 

### **Solution**: 
Obnoxious ghost text
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/f85530f5-9bf8-470b-8018-367f162ddc51">

As you can see I've changed the preview but we also need to change it for the actual copy and paste component here: 
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/c0cb3228-8bb1-4a54-a566-f24ee8da04f3">

Let me know if this is something I can do! Happy to learn.

**Comment by AlexVanK** [comment]
Good points! I updated the code ;)
